[package]
name = "cvlab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
egui = "0.18.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"